### PR TITLE
Fix: get_key inspection fail on autoretry_for

### PR DESCRIPTION
**Pull request by pkariz**
This is a proposed fix for the issue #74

### CODE REVIEW

**Comment by dotpmrcunha** [comment]
Hi all,

Is this merge request going to be accepted?

This seems to solve my issue with autoretry_for plus once={'keys': [...]}

Regards,
Pedro

**Comment by mathiasose** [comment]
I ran into this problem too. Any plans for a release that includes this fix soon?

**Comment by cameronmaske** [comment]
@mathiasose I'll push a release for 2.0.1 with this included shortly!

**Comment by cameronmaske** [comment]
Should be live, sorry again for the delay.

**Comment by mathiasose** [comment]
:clap: Thanks!

**Pull request merged**
