### PR TITLE
File backend

### PR DESCRIPTION
**Pull request by xuhcc**
This backend allows celery-once to use files for locking.

### CODE REVIEW

**Comment by cameronmaske** [comment]
@xuhcc This looks excellent! Thank you for your contribution. Anything more to do on your end, or is this ready for review?

**Comment by xuhcc** [comment]
@cameronmaske Yes, it's ready for review.

**Comment by cameronmaske** [comment]
@xuhcc Overall looks great! 
Could you grant me permission to make some minor changes (naming consistency) by enabling [Allow edits from maintainers](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by xuhcc** [comment]
Yes, please. I already set the " Allow edits from maintainers." flag

**Comment by cameronmaske** [comment]
Ah, I think I'm confused on how to make PR changes locally on the git CLI, I'll merge this as is, and do the changes separately for now.

**Comment by cameronmaske** [comment]
@xuhcc This is live in version `2.1.0`. Thanks again for the contribution!

**Pull request merged**
